version: '3.9'

services:
  nodejs:
    container_name: nb_nodejs
    restart: always
    build:
      context: .
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
    networks:
      - noticer

networks:
  noticer:
    external: true